export enum Article {
  ABOUT = 'ABOUT',
  SKILLS = 'SKILLS',
  PROJECTS = 'PROJECTS',
  CONTACTS = 'CONTACTS',
}

export enum Transition {
  NAV_VISIBLE = 'NAV_VISIBLE',
  NAV_TRANSITION = 'NAV_TRANSITION',
  ARTICLE_TRANSITION = 'ARTICLE_TRANSITION',
  ARTICLE_VISIBLE = 'ARTICLE_VISIBLE',
}
